### ISSUE TITLE
Appunti per la prof

### ISSUE THREAD

**Issue by guglielmobartelloni** [guglielmobartelloni/appunti-analisi-2#21]
Stavo pensando che magari si potrebbero dare alla prof questi appunti per fornire delle dispense in più agli alunni del futuro. Magari ripulendo un po' e facendo i disegni mancanti.

**Comment by Martinligabue** [comment]
non vedo perché no

**Comment by guglielmobartelloni** [comment]
## Aggiornamento

Ho chiesto oggi alla prof se le poteva interessare la cosa mi mi sa che ha frainteso e non ne voleva sapere, poi lo chiederò meglio
