### ISSUE TITLE
Impossibilità nel seguire le lezioni

### ISSUE THREAD

**Issue by guglielmobartelloni** [guglielmobartelloni/appunti-analisi-2#8]
Purtroppo per problemi di salute non potrò più seguire le lezioni di analisi, cercherò comunque di tenere gli appunti aggiornati ma potrebbe volerci di più

**Comment by Martinligabue** [comment]
se vuoi posso passarti le registrazioni solo audio, se si dovessero sentire male so di un'altra ragazza che le registra
i miei appunti non son particolarmente adatti, ma anche di quelli conosco chi ne prende di buoni

**Comment by guglielmobartelloni** [comment]
Ah grazie mille, più che le registrazioni avrei bisogno degli appunti scritti in modo da poterli ricopiare. Al momento li sto prendendo da una ragazza che però non c'è sempre, per esempio domani non me li può dare. Se conosci qualcuno che ce l'ha mi faresti un grande favore, grazie in anticipo.

**Comment by Martinligabue** [comment]
quelli che trovo te li carico in una cartella temporanea che creerò nella repo

**Comment by guglielmobartelloni** [comment]
Perfetto ti ringrazio

**Comment by Martinligabue** [comment]
[2022-11-30.pdf](https://github.com/guglielmobartelloni/appunti-analisi-2/files/10122431/2022-11-30.pdf)
ah posso caricarli nei commenti i file
questa è la parte pre-pausa, i miei appunti non so quanto siano leggibili per altri, ma intanto posso caricarteli subito che mi dici se ci son problemi o se posso essere più chiaro nell'altra parte, quando finisco ti passo quello completo, chiederò a chi è presente oggi che conosco di passarmi poi anche i loro

**Comment by guglielmobartelloni** [comment]
Perfetto, grazie mille. Vai tranquillo comunque che ha detto uno che me li passa quindi dovrei avere anche i suoi. Comunque grazie davvero

**Comment by Martinligabue** [comment]
[2022-11-30.pdf](https://github.com/guglielmobartelloni/appunti-analisi-2/files/10123618/2022-11-30.pdf)
in ogni caso tieni se dovesse servire

**Comment by Martinligabue** [comment]
direi che si può chiudere, le lezioni son finite

**Comment by guglielmobartelloni** [comment]
Si a questo punto. Mi manca solo da copiare le ultime lezioni che mi hanno passato oggi 👌
